### ISSUE TITLE
How to set Message Header Properties for use by Message Selectors in Mulesoft Solace Connector

### ISSUE THREAD

**Issue by vasanth-srg** [solace-iot-team/solace-mule-connector#3]
Hi,
Is there any way to set messages’ header field and property values in Mulesoft Solace Connector?

Thanks in Advance,
Vasanth

**Comment by 195858** [comment]
This initial open source version of the connector does not support message headers.

Solace has created an official Mulesoft Connector which is currently in Early Access mode.
It may have added access to headers in addition to a number of other additional features.

You can request access to the early access group here:
https://solace.community/group/3-solace-early-access-mulesoft-connector

At this time I have no plans to enhance the functionality of this open source version.
